soup wast address.json
soup wast align.json
soup wast binary.json
soup wast binary-leb128.json
soup wast block.json
soup wast br.json
soup wast br_if.json
soup wast br_table.json
soup wast bulk.json
soup wast call.json
soup wast call_indirect.json
soup wast comments.json
soup wast const.json
soup wast conversions.json
soup wast custom.json
soup wast data.json
soup wast elem.json
soup wast endianness.json
soup wast exports.json
soup wast extended-const.json
soup wast f32.json
soup wast f32_bitwise.json
soup wast f32_cmp.json
soup wast f64.json
soup wast f64_bitwise.json
soup wast f64_cmp.json
soup wast fac.json
soup wast float_exprs.json
soup wast float_literals.json
soup wast float_memory.json
soup wast float_misc.json
soup wast forward.json
soup wast func.json
soup wast func_ptrs.json
soup wast global.json
soup wast i32.json
soup wast i64.json
soup wast if.json
soup wast imports.json
soup wast inline-module.json
soup wast int_exprs.json
soup wast int_literals.json
soup wast labels.json
soup wast left-to-right.json
soup wast linking.json
soup wast load.json
soup wast local_get.json
soup wast local_set.json
soup wast local_tee.json
soup wast loop.json
soup wast memory.json
soup wast memory_copy.json
soup wast memory_fill.json
soup wast memory_grow.json
soup wast memory_init.json
soup wast memory_redundancy.json
soup wast memory_size.json
soup wast memory_trap.json
soup wast names.json
soup wast nop.json
soup wast obsolete-keywords.json
soup wast ref_func.json
soup wast ref_is_null.json
soup wast ref_null.json
soup wast return.json
soup wast return_call.json
soup wast return_call_indirect.json
soup wast select.json
soup wast skip-stack-guard-page.json
soup wast stack.json
soup wast start.json
soup wast store.json
soup wast switch.json
soup wast table.json
soup wast table-sub.json
soup wast table_copy.json
soup wast table_fill.json
soup wast table_get.json
soup wast table_grow.json
soup wast table_init.json
soup wast table_set.json
soup wast table_size.json
soup wast token.json
soup wast traps.json
soup wast type.json
soup wast unreachable.json
soup wast unreached-invalid.json
soup wast unreached-valid.json
soup wast unwind.json
soup wast utf8-custom-section-id.json
soup wast utf8-import-field.json
soup wast utf8-import-module.json
soup wast utf8-invalid-encoding.json

cd memory64
..\soup wast address64.json
..\soup wast align64.json
..\soup wast binary_leb128_64.json
..\soup wast bulk64.json
..\soup wast call_indirect64.json
..\soup wast endianness64.json
..\soup wast float_memory64.json
..\soup wast load64.json
..\soup wast memory64.json
..\soup wast memory64-imports.json
..\soup wast memory_copy64.json
..\soup wast memory_fill64.json
..\soup wast memory_grow64.json
..\soup wast memory_init64.json
..\soup wast memory_redundancy64.json
..\soup wast memory_trap64.json
..\soup wast table64.json
..\soup wast table_copy64.json
..\soup wast table_copy_mixed.json
..\soup wast table_fill64.json
..\soup wast table_get64.json
..\soup wast table_grow64.json
..\soup wast table_init64.json
..\soup wast table_set64.json
..\soup wast table_size64.json
cd ..

cd multi-memory
..\soup wast address0.json
..\soup wast address1.json
..\soup wast align0.json
..\soup wast binary0.json
..\soup wast data0.json
..\soup wast data1.json
..\soup wast data_drop0.json
..\soup wast exports0.json
..\soup wast float_exprs0.json
..\soup wast float_exprs1.json
..\soup wast float_memory0.json
..\soup wast imports0.json
..\soup wast imports1.json
..\soup wast imports2.json
..\soup wast imports3.json
..\soup wast imports4.json
..\soup wast linking0.json
..\soup wast linking1.json
..\soup wast linking2.json
..\soup wast linking3.json
..\soup wast load0.json
..\soup wast load1.json
..\soup wast load2.json
..\soup wast memory-multi.json
..\soup wast memory_copy0.json
..\soup wast memory_copy1.json
..\soup wast memory_fill0.json
..\soup wast memory_grow.json
..\soup wast memory_init0.json
..\soup wast memory_size0.json
..\soup wast memory_size1.json
..\soup wast memory_size2.json
..\soup wast memory_size3.json
..\soup wast memory_size_import.json
..\soup wast memory_trap0.json
..\soup wast memory_trap1.json
..\soup wast start0.json
..\soup wast store0.json
..\soup wast store1.json
..\soup wast store2.json
..\soup wast traps0.json
cd ..

cd exceptions
..\soup wast tag.json
..\soup wast throw.json
..\soup wast throw_ref.json
..\soup wast try_table.json
cd ..

pause
